In [1]:
print("19881A05H2 Amaan Smd CSE-C")
import pandas as ps
import numpy as np

19881A05H2 Amaan Smd CSE-C


In [2]:
print("_______Answer1_______")

_______Answer1_______


In [5]:
dataf=ps.DataFrame({'X':[78,85,96,80,86], 'Y':[84,94,89,83,86],'Z':[86,97,96,72,83]} )

In [6]:
print(dataf)

    X   Y   Z
0  78  84  86
1  85  94  97
2  96  89  96
3  80  83  72
4  86  86  83


In [7]:
print("________Answer 2__________")

________Answer 2__________


In [8]:
datadic=exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}

In [9]:
lab = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

In [11]:
dataf2=ps.DataFrame(datadic,index=lab)

In [12]:
print(dataf2)

        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
d      James    NaN         3      no
e      Emily    9.0         2      no
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
j      Jonas   19.0         1     yes


In [13]:
print("________Answer 3__________")

________Answer 3__________


In [14]:
print(dataf2[['name','score']])

        name  score
a  Anastasia   12.5
b       Dima    9.0
c  Katherine   16.5
d      James    NaN
e      Emily    9.0
f    Michael   20.0
g    Matthew   14.5
h      Laura    NaN
i      Kevin    8.0
j      Jonas   19.0


In [15]:
print("________Answer 4__________")

________Answer 4__________


In [16]:
interval=ps.DataFrame({"X":[1,2,3,4,5,6]},
index=ps.IntervalIndex.from_breaks([1,2,3,4,5,6,7]))

In [17]:
print(interval)

        X
(1, 2]  1
(2, 3]  2
(3, 4]  3
(4, 5]  4
(5, 6]  5
(6, 7]  6


In [18]:
print(interval.index)

IntervalIndex([(1, 2], (2, 3], (3, 4], (4, 5], (5, 6], (6, 7]],
              closed='right',
              dtype='interval[int64]')


In [19]:
interval=ps.DataFrame({"X":[1,2,3,4,5,6]},
index=ps.IntervalIndex.from_tuples([(1,2),(2,3),(3,4),(4,5),(5,6),(6,7)]))

In [20]:
print(interval)

        X
(1, 2]  1
(2, 3]  2
(3, 4]  3
(4, 5]  4
(5, 6]  5
(6, 7]  6


In [21]:
print(interval.index)

IntervalIndex([(1, 2], (2, 3], (3, 4], (4, 5], (5, 6], (6, 7]],
              closed='right',
              dtype='interval[int64]')


In [22]:
interval=ps.DataFrame({"X":[1,2,3,4,5,6]},
index=ps.IntervalIndex.from_arrays([1,2,3,4,5,6],[2,3,4,5,6,7]))

In [23]:
print(interval)
print(interval.index)

        X
(1, 2]  1
(2, 3]  2
(3, 4]  3
(4, 5]  4
(5, 6]  5
(6, 7]  6
IntervalIndex([(1, 2], (2, 3], (3, 4], (4, 5], (5, 6], (6, 7]],
              closed='right',
              dtype='interval[int64]')


In [28]:
data=ps.read_csv('data.csv')

In [29]:
print("_________Answer 5__________")

_________Answer 5__________


In [30]:
print(data.shape)

(5, 6)


In [31]:
print(data.shape[0],data.shape[1])

5 6


In [32]:
print("columns\n",data.columns)

columns
 Index(['Year', 'WHO region', 'Country', 'Beverage Types', 'Display Value',
       'Unnamed: 5'],
      dtype='object')


In [33]:
print(data)

   Year  WHO region          Country         Beverage Types Display Value  \
0   NaN        1986  Western Pacific               Viet Nam          Wine   
1   NaN        1986         Americas                Uruguay         Other   
2   NaN        1985           Africa           Cte d'Ivoire          Wine   
3   NaN        1986         Americas               Colombia          Beer   
4   NaN        1987         Americas  Saint Kitts and Nevis          Beer   

   Unnamed: 5  
0        0.00  
1        0.50  
2        1.62  
3        4.27  
4        1.98  


In [35]:
print("________Answer 6______")
arr1=ps.Series([2, 4, 6, 8, 10])

________Answer 6______


In [36]:
arr2=ps.Series([1, 3, 5, 7, 10] )

In [37]:
print(arr1==arr2)

0    False
1    False
2    False
3    False
4     True
dtype: bool


In [38]:
print(arr1>arr2)

0     True
1     True
2     True
3     True
4    False
dtype: bool


In [39]:
print(arr1<arr2)

0    False
1    False
2    False
3    False
4    False
dtype: bool


In [40]:
print("________Answer 7______")

________Answer 7______


In [41]:

student1 = ps.DataFrame({
        'sid': ['S1', 'S2', 'S3', 'S4', 'S5'],
         'name': ['Danniella Fenton', 'Ryder Storey', 'Bryce Jensen', 'Ed Bernal', 'Kwame Morin'], 
        'marks': [200, 210, 190, 222, 199]})

student2 = ps.DataFrame({
        'sid': ['S4', 'S5', 'S6', 'S7', 'S8'],
        'name': ['Scarlette Fisher', 'Carla Williamson', 'Dante Morse', 'Kaiser William', 'Madeeha Preston'], 
        'marks': [201, 200, 198, 219, 201]})

In [42]:
mergeddata=ps.concat([student1,student2])

In [43]:
print(mergeddata)

  sid              name  marks
0  S1  Danniella Fenton    200
1  S2      Ryder Storey    210
2  S3      Bryce Jensen    190
3  S4         Ed Bernal    222
4  S5       Kwame Morin    199
0  S4  Scarlette Fisher    201
1  S5  Carla Williamson    200
2  S6       Dante Morse    198
3  S7    Kaiser William    219
4  S8   Madeeha Preston    201


In [44]:
print("________Answer 8_________")

________Answer 8_________


In [45]:
l=[1,2,3,4,5]
nplist=np.array(l)

In [46]:
print(l,nplist)

[1, 2, 3, 4, 5] [1 2 3 4 5]


In [47]:
print("________Answer 9_________")

________Answer 9_________


In [48]:
rang=np.arange(2,11).reshape(3,3)

In [49]:
print(rang)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [50]:
print("________Answer 10_________")

________Answer 10_________


In [51]:
randarray=np.random.random((3,3,3))

In [52]:
print(randarray)

[[[0.52029332 0.36896276 0.43229669]
  [0.6548431  0.02325664 0.26175894]
  [0.63529623 0.2905097  0.5292741 ]]

 [[0.36117143 0.24767542 0.95812216]
  [0.94433679 0.67911575 0.79591697]
  [0.86521253 0.00552247 0.34473563]]

 [[0.34046223 0.16255902 0.36174328]
  [0.66990767 0.16752599 0.98576716]
  [0.92333532 0.06499017 0.23987738]]]
